# Generated by Django 5.1.7 on 2025-05-09 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Academics',
            new_name='Student_Past_Academics',
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='program.program'),
            preserve_default=False,
        ),
    ]
