# Generated by Django 5.1.7 on 2025-05-23 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('student', '0002_rename_student_academics_student_past_academics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='level.program_level'),
            preserve_default=False,
        ),
    ]
