# Generated by Django 5.1.7 on 2025-05-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mcq',
            },
        ),
        migrations.CreateModel(
            name='Mcq_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_correct', models.SmallIntegerField(default=0)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq')),
            ],
            options={
                'db_table': 'mcq_question',
            },
        ),
    ]
