# Generated by Django 5.1.7 on 2025-05-22 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('mcq', '0001_initial'),
        ('program', '0001_initial'),
        ('student', '0002_rename_student_academics_student_past_academics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='level.program_level'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
        migrations.CreateModel(
            name='McqAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mcq.mcq_question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='student.student')),
            ],
            options={
                'db_table': 'mcq_answer',
            },
        ),
    ]
