# Generated by Django 5.1.7 on 2025-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_mcq_level_mcq_program_mcqanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
